name: Discord GitHook

on: [push]

jobs:
  report-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: "8.0.292+10"
          distribution: 'adopt'
      - name: Run Discord Webhook
        uses: Vladimir-Urik/pc-discord-webhook@master
        with:
          id: "837452458355195975"
          token: "C2fJLCyvYrzPBMwKSa0kazIqeNhblYlu0A9v-KsQ6uglsOjFsXGcdXUrIW0WJM9jrngG"
